### ISSUE TITLE
security in ttn

### ISSUE THREAD

**Issue by OwenBrotherwood** [TheThingsNetworkDenmark/TheThingsNetworkDenmark#6]
One question I have received was on the lines of security, hacking etc.

Opinionated:
The Things Network is enabling things, security etc can be a concern but the things network is enabling creation of things to use the things network ans security is possibly an issue but the mission is to enable things and security starts on the thing one is trying to enable

**Comment by OwenBrotherwood** [comment]
The Ethics of Things (EoT) is also something that may or may not be relevant to this issue with academic work in the area
https://www.itu.dk/om-itu/presse/nyheder/forskere-vil-goere-internet-of-things-etisk

https://virt-eu.nexacenter.org/

As IoT TTN and possible usage by kids in coding to create a thing to be used on TTN, security for kids becomes an issue if taken this far.

Security for kids has been a very key issue for the microbit.org and it's efforts in BBC timespace for ensuring kids security with forums, code posting and other aspects being a very important part of the total solution from the foundation.

'tis better to take this up front to ensure the best thing for denmark

**Comment by quillis** [comment]
Security is just one (though incredibly important) aspect of ethical thinking and in IoT type devices this becomes crucial especially because there are so many points of attack in these services (hardware, communication protocols, data). There are huge concerns with cyber security in this space but not a lot of standards and not a lot of simple answers. 

What data to collect, how and why is another set of ethical decisions. Who gets access to data, who gets to make decisions, how are data flows controlled and analyzed is another set of moral reasoning. Where are these issues getting hashed out and discussed? If you are creating technologies how do you start thinking about these? 

These are the questions that are project - VIRT-EU is trying to address. We don't yet have any answers (we are just a month into the project), but we would love to have more conversations about it!

**Comment by OwenBrotherwood** [comment]
LoRaWAN Security - The Things Network Webinar by Johan Stokking
A technical presentation
https://www.youtube.com/watch?v=Nu_yZelDMZI

**Comment by OwenBrotherwood** [comment]
Closed and await  VIRT-EU results: in the meantime, security is documented in TTN standard material
